### PR TITLE
RA-1815: Collapsible 'if' statements should be merged

### PR DESCRIPTION
**Pull request by kdaud**
Ticket id: https://issues.openmrs.org/browse/RA-1815
Merged collapsible if statements in the code base

### CODE REVIEW

**Comment by HerbertYiga** [comment]
@kdaud  go on and claim this ticket to show that you are doing works around it

**Comment by kdaud** [comment]
> @kdaud go on and claim this ticket to show that you are doing works around it

Any one is free to claim the ticket

**Comment by sacull** [comment]
@kdaud Wait, why are you abandoning him? You just need to fix a few code indentations (there is one code level less after removing one if statement) and the PR will be good.

**Comment by kdaud** [comment]
> @kdaud Wait, why are you abandoning him? You just need to fix a few code indentations (there is one code level less after removing one if statement) and the PR will be good.

@sacull I was enrolled on this ticket before and just found out that I was unassigned from it by some senior dev. I reclaimed it again and the same instance happened by the same dev. I think the ticket needed some one new with the workflow and decided not to reclaim it for the third time because I knew a similar instance would happen.
Well I just knew the dev wishes me to advance to a more technical skill set higher than this. Currently am enrolled with some work within the community and am ok with abandoning this ticket, and will be glad to make review for any contributor

**Comment by sacull** [comment]
@kdaud I understand. So don't forget to close this PR. ;)

**Comment by kdaud** [comment]
Any one can pick up from here

**Comment by Shayyan88** [comment]
I submitted a PR for it.

**Pull request closed without merging**
