### PR TITLE
RA-1387: Upgrade FontAwesome from 3.x to latest (5+)

### PR DESCRIPTION
**Pull request by segunolalive**
## JIRA TICKET NAME
[RA-1387: Upgrade FontAwesome from 3.x to latest (4.7 or 5+)](https://issues.openmrs.org/browse/RA-1387)

### SUMMARY
The latest version of FontAwesome (5xx) has a much richer set of icons. As we expand functionality of our RefApp implementations, we are running out of unique and appropriate icons.

This PR updates the FontAwesome dependency to version 5

### CODE REVIEW

**Comment by dkayiwa** [comment]
@segunolalive are those icons any different from these? https://demo.openmrs.org/openmrs/uicommons/icons.page

**Comment by segunolalive** [comment]
Yes. They are.

**Comment by dkayiwa** [comment]
How are they different? Can you give examples?

**Comment by segunolalive** [comment]
I'm sorry. The affected icons belong to that list

**Comment by dkayiwa** [comment]
I do not seem to understand your response. Can you be more direct?

**Comment by segunolalive** [comment]
The affected icons belong to the list on [this link](https://demo.openmrs.org/openmrs/uicommons/icons.page)

**Comment by dkayiwa** [comment]
So does this mean the icons are not any different? (back to my earliest question)

**Comment by segunolalive** [comment]
They are not different

**Comment by dkayiwa** [comment]
If the are the same, does this mean that the upgrade is not giving us any added value?

**Comment by segunolalive** [comment]
It's difficult for me to make that conclusion because FontAwesome adds new icons in new releases which is why this ticket was created.

**Comment by dkayiwa** [comment]
I was trying to look at the list and the number of icons looks almost the same. Did you get a chance to look at the release notes for what changed between the versions?

**Comment by segunolalive** [comment]
icons in version 3 use the `icon-` prefix while is version 4, it was changed to `fa-` but version 5 introduces new prefixes a well as changes to icon names

[upgrading from 4 to 5](https://fontawesome.com/how-to-use/upgrading-from-4)
[Upgrading from 3 to 4](https://github.com/FortAwesome/Font-Awesome/wiki/Upgrading-from-3.2.1-to-4)

**Comment by dkayiwa** [comment]
From your experience in working on this, do you see practical value for us to upgrade?

**Comment by segunolalive** [comment]
Honestly, I don't

**Comment by mogoodrich** [comment]
We probably should add some of these comments to the ticket?

**Comment by segunolalive** [comment]
I think we should not upgrade to the dependencies but use both version 3xx as well as 5x. There should be no classname collisions since version 3 class names are `icon-*` while version 5 class names are `fa fa-*`

**Comment by dkayiwa** [comment]
@segunolalive ahh, that looks like an interesting idea! 😊 
Can you do a pull request for it and i take a look?

**Comment by segunolalive** [comment]
Done

**Comment by Charpell** [comment]
Looks good to me

**Comment by andela-dbamidele** [comment]
Great Job 👍

**Comment by dkayiwa** [comment]
@segunolalive do the upgraded icons also show up at? http://localhost:8080/openmrs/uicommons/icons.page

**Comment by segunolalive** [comment]
No. That is a list of icons from version 3

**Comment by dkayiwa** [comment]
So which url do i use to see the new ones?

**Comment by segunolalive** [comment]
I don’t know yet. I don’t even know how this page (http://localhost:8080/openmrs/uicommons/icons.page <http://localhost:8080/openmrs/uicommons/icons.page>) is generated.

**Pull request merged**
