### PR TITLE
RA-923: Manage Extension page in the UI

### PR DESCRIPTION
**Pull request by CeciliaHwang**
This PR adds a Manage Extensions page to the UI based off of the Manage Apps page. It provides the ability to enable and disable built-in extensions.

Ticket ID: https://issues.openmrs.org/browse/RA-923

New "Manage Extensions" button on system administration page:
Screenshot 2020-02-24 at 10 50 00

Manage Extensions page:
Screenshot 2020-02-24 at 12 00 02

### CODE REVIEW

**Comment by dkayiwa** [comment]
@CeciliaHwang did you take a look at this? https://wiki.openmrs.org/display/docs/Pull+Request+Tips

**Comment by CeciliaHwang** [comment]
@dkayiwa Thanks for the information. Looks like I missed squashing the commits--I made this adjustment and squashed the two commits into one. Was there anything else that I missed? I'm a bit new to github/git, so thanks for your patience while I learn.

**Comment by dkayiwa** [comment]
Can you include the ticket id in the commit message as advised at? https://wiki.openmrs.org/display/docs/Pull+Request+Tips

**Comment by CeciliaHwang** [comment]
@dkayiwa Thanks again for the feedback! I adjusted the commit message to include the ticket id.

**Comment by sherrif10** [comment]
cc @dkayiwa  @CeciliaHwang

**Comment by sherrif10** [comment]
Hello @CeciliaHwang  @dkayiwa  seems am not seeing some extensions  links forexample org.openmrs.module.registrationapp.registerPatient.

**Comment by dkayiwa** [comment]
@sherrif10 isn't that an app and hence supposed to be under manage apps instead of extensions?

**Comment by sherrif10** [comment]
@dkayiwa True  thanks i tested and it work as expected

**Pull request merged**
