### PR TITLE
RA-1817: @Override used for overriding and implementing methods

### PR DESCRIPTION
**Pull request by Wandji69**
Adding the ```@Override``` annotation for overriding and implementing methods
https://issues.openmrs.org/browse/RA-1817

### CODE REVIEW

**Review by sacull — APPROVED** [review]
Please add a link to the JIRA ticket in the PR description and you'll be fine.

**Comment by sacull** [comment]
@Wandji69 Are you still working on this PR?

**Comment by Wandji69** [comment]
Yes. I had added the changes requested.

**Comment by sacull** [comment]
So please add a link to the ticket in JIRA to the PR description.

**Review by sacull — APPROVED** [review]
Now it looks good because the reviewer does not have to search JIRA for the ticket that this PR applies to. ;)

**Pull request merged**
