### PR TITLE
Fixed a couple typos in comments

### PR DESCRIPTION
**Pull request by ddworken**

### CODE REVIEW

**Comment by dkayiwa** [comment]
@ddworken can you squash these commits into one?

**Comment by robbyoconnor** [comment]
He can squash them and it will be reflected in the PR

**Comment by robbyoconnor** [comment]
Remove the XSS vulnerability commit from this PR if you would like your task approved.

**Comment by ddworken** [comment]
Sorry about that, I went ahead and split it into two separate commits/PRs/branches.

**Pull request merged**
