### PR TITLE
Remove system administration OWA in ReferenceApplication

### PR DESCRIPTION
**Pull request by sherrif10**
https://issues.openmrs.org/browse/RA-1951 cc @dkayiwa @ibacher

### CODE REVIEW

**Comment by sherrif10** [comment]
cc @ibacher  @dkayiwa .

**Comment by dkayiwa** [comment]
@sherrif10 are these all the references to the system administration OWA?

**Comment by sherrif10** [comment]
@dkayiwa  Yes .Thanks.

**Comment by sherrif10** [comment]
Hello @dkayiwa , i think we are good to do with this. After looking into how  Live server logs implementation, it was not added into referenceapplication, it was however added as an accessible page with in https://github.com/openmrs/openmrs-owa-sysadmin/tree/master/app/js/serverLog

**Comment by dkayiwa** [comment]
There are still more references to the sysadmin app

**Comment by sherrif10** [comment]
Ok let me create a follow-up commit from sysadmin app. Thnks

**Comment by sherrif10** [comment]
Hello @dkayiwa , with in this module, i seem not be seeing the references to sysadmin app , We are only remaininng with  Live server log page which i think it was implemented in https://github.com/openmrs/openmrs-owa-sysadmin/tree/master/app/js/serverLog .where havent figured out how it was configured to be called. Any suggestions

**Comment by dkayiwa** [comment]
https://github.com/openmrs/openmrs-module-referenceapplication/search?q=systemAdministration

**Comment by sherrif10** [comment]
Hello @dkayiwa ,I think for extensionPointId, we need to leave them as it is since the redirect doesnot come from owa-sysadmin  but rather some from coreapps and other modules!

**Comment by dkayiwa** [comment]
Will the url exist when redirected to?

**Comment by sherrif10** [comment]
The url will not be able to exist when redirected to, Actually there will be no redirections to urls with owa-system

**Comment by dkayiwa** [comment]
So why don't you want to remove them?

**Comment by sherrif10** [comment]
Have been only removing url with   "url": "owa/SystemAdministration/index.html#/system-info", only , i think having the same extensionPointId is fine, if i remove other urls like https://github.com/openmrs/openmrs-module-referenceapplication/blob/master/omod/src/main/resources/apps/manageExtensions_extension.json  , it means we are getting rid of this function which i think is not the case .

**Comment by sherrif10** [comment]
Thanks @dkayiwa

**Pull request merged**
